Feature/api design 1.0
MideTechnology/endaq-python-cloud pull request #13
Opened 2021-10-12 14:35 UTC by SamRagusa

One thing that should probably still be added is setting attributes from a pandas dataframe.

2021-10-12 15:16 UTC, StokesMIDE requested changes
The only real request for a change is the bit about using `self.domain`; the rest are mostly comments and suggestions.

2021-10-12 18:41 UTC, SamRagusa commented on endaq/cloud/core.py
> +            if f_data['device'] is not None and len(f_data['device']) > 0:
This doesn't work, if `f_data['device']` is None, then what you're suggesting will evaluate to True, but I need it to evaluate to False in that case.   (I've also tested it and it fails in that case)

2021-10-12 18:56 UTC, StokesMIDE requested changes
One minor change and all's good.

2021-10-12 18:56 UTC, StokesMIDE commented on endaq/cloud/core.py
> +TODO: Rewrite docstrings (pref. before implementing methods)
Just delete this line and I think it's good to go.

2021-10-12 19:02 UTC, merged

2021-10-13 14:30 UTC, CrepeGoat commented on endaq/cloud/core.py
> +            if f_data['device'] is not None and len(f_data['device']) > 0:
@StokesMIDE correct me if I'm wrong, but I think this is what you're getting at:
```pycon
>>> def v1(obj):
...     return (obj is not None and len(obj) > 0)
...
>>> def v2(obj):
...     return bool(obj)
...
>>> o = None
>>> assert v1(o) == v2(o)
>>> o = []
>>> assert v1(o) == v2(o)
>>> o = ["non-empty list"]
>>> assert v1(o) == v2(o)
```

In that case, I think you mean `if f_data['device']`