Function Access Change
MideTechnology/endaq-python-cloud pull request #18
Opened 2021-11-04 18:50 UTC by SamRagusa

- Made core cloud data functions accessible from `endaq.cloud.*` rather than `endaq.cloud.core.*`

2021-11-04 18:51 UTC, SamRagusa commented
@CrepeGoat  is this going to mess up the docs?  Also will we run into the same problem we had with `endaq.plot` where we had to define `__all__`?

2021-11-04 18:53 UTC, StokesMIDE requested changes
Add a newline to the end of the file and I'd say it's good to go.

2021-11-04 18:55 UTC, CrepeGoat commented
> is this going to mess up the docs?

We'd have to edit them to not look for the `core` module, yeah. but tbh if we're going to make changes, I'd rather do it sooner before people get comfortable with having a certain module in a certain spot.

> Also will we run into the same problem we had with `endaq.plot` where we had to define `__all__`?

Probably, yeah. Even if we don't explicitly see the problem come up, I'd like to do the `__all__` bit anyway? unless we find a better way to reject unwanted imports... (but I will note it's in a few files in `endaq.ide` as well, so it's not a new/strange thing per se.)

2021-11-04 18:56 UTC, CrepeGoat requested changes
suggested thing, and also adding `__add__` pre-emptively to `core`

2021-11-04 18:56 UTC, CrepeGoat commented on endaq/cloud/__init__.py
> +from .core import *
```suggestion
from .core import *

```

2021-11-04 19:00 UTC, StokesMIDE commented
+1 on the addition of `__all__`. I think it's good practice for a public package like this.

2021-11-04 19:46 UTC, SamRagusa commented
I've set the `__all__` variable on endaq.cloud.core

2021-11-04 19:59 UTC, CrepeGoat approved these changes
looks good

2021-11-04 20:26 UTC, StokesMIDE commented on endaq/cloud/core.py
>  ENV_DEVELOP = "https://mnsz98xs64.execute-api.us-west-2.amazonaws.com/develop"
These really shouldn't be in the distributed package

2021-11-04 20:26 UTC, StokesMIDE approved these changes

2021-11-05 14:27 UTC, SamRagusa commented on endaq/cloud/core.py
>  ENV_DEVELOP = "https://mnsz98xs64.execute-api.us-west-2.amazonaws.com/develop"
Why, they can't access anything from within them.   What are you worried could happen if they are?   Having these be easily accessible to the internal Mide people is helpful

2021-11-09 16:37 UTC, merged