Added Various Cloud Scripting Utilities
MideTechnology/endaq-python-cloud pull request #20
Opened 2021-11-10 15:07 UTC by SamRagusa

- Added a function to help producing the output formatting desired by a custom enDAQ cloud report
- Added a function to help develop custom enDAQ cloud scripts, by running them as if it was actually being run on the cloud

2021-11-10 15:14 UTC, StokesMIDE commented on endaq/cloud/scripting.py
> +        api_access_url = 'https://mnsz98xs64.execute-api.us-west-2.amazonaws.com/develop/api/v1/'
Isn't there already a dict with the URLs in `core.py`, or would using it cause circular imports?

2021-11-10 15:24 UTC, SamRagusa commented on endaq/cloud/scripting.py
> +        api_access_url = 'https://mnsz98xs64.execute-api.us-west-2.amazonaws.com/develop/api/v1/'
They are defined there, good point.  I'll change it to use those now

2021-11-10 15:31 UTC, SamRagusa commented
I wanted to make sure the new functions are handled properly with respect to the __init__ file, I'll make those edits after this meeting.

2021-11-11 15:38 UTC, SamRagusa commented
I made the changes I mentioned and here's a colab using them:

https://colab.research.google.com/drive/1v2RTu1vBDsBQer1qZXoXlhjMlRTeXke_?usp=sharing

2021-11-11 16:43 UTC, CrepeGoat requested changes
I think either
- setup.py needs to add plotly as a dependency, or
- plotly needs to be an optional import

2021-11-11 16:43 UTC, CrepeGoat commented on endaq/cloud/scripting.py
> +    if environment == 'master':
name this to `"production"` instead of `"master"`?

2021-11-11 16:43 UTC, CrepeGoat commented on endaq/cloud/scripting.py
> +import plotly.io as pio
plotly added here -> add dependency to setup.py

2021-11-11 17:01 UTC, CrepeGoat approved these changes

2021-11-11 17:05 UTC, merged

2021-11-11 18:08 UTC, StokesMIDE approved these changes
Approving, although it might be worthwhile to do the JSON sanitization now.

2021-11-11 18:08 UTC, StokesMIDE commented on endaq/cloud/scripting.py
> +    return "[" + ", ".join([v.to_json()[:-1] + ', "title": "' + k + '"}' for k, v in name_to_fig.items()]) + "]"
It might be better to create an actual list of dictionaries (using `Figure.to_dict()`), add the titles to the dictionaries, and then convert the whole thing to json (via `json.dumps()`)... if for no other reason, it'll make sure the title is sanitized.

2021-11-11 18:08 UTC, StokesMIDE commented on endaq/cloud/scripting.py
> +        api_access_url = ENV_DEVELOP + '/api/v1/'
In the future, we might want to replace the three `ENV_*` variables with a single dictionary, with master/staging/develop as the keys. I think I just used the URL variables directly in the kwargs, but the docstrings would render better if I also used keywords like this. It doesn't affect this PR, though.